services:
    app:
        image: serversideup/php:8.3-fpm-apache
        ports:
            - '${APP_PORT:-8088}:8080'
        environment:
            SSL_MODE: 'off'
            PHP_OPCACHE_ENABLE: '1'
            AUTORUN_ENABLED: 'false'
            APACHE_DOCUMENT_ROOT: '/var/www/html/public'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy

    postgres:
        image: 'postgres:16-alpine'
        ports:
            - '${FORWARD_DB_PORT:-15432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE:-tpa3}'
            POSTGRES_USER: '${DB_USERNAME:-tpa}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-tpa123}'
        volumes:
            - 'sail-postgres:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-tpa} -d ${DB_DATABASE:-tpa3}"]
            interval: 5s
            retries: 5
            timeout: 5s

    redis:
        image: 'redis:7-alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-16379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            retries: 5
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    sail-postgres:
        driver: local
    sail-redis:
        driver: local
